language: node_js
node_js:
  - "5.1"
services:
  - mongodb
before_script:
  - sleep 15
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node_modules/protractor/bin/webdriver-manager update --standalone --firefox
  - node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - sleep 3
  - node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update --standalone --firefox
  - node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - sleep 3
  - bower install
  - npm install -g gulp
  - npm start
  - sleep 3
script: gulp